#docker-compose.yaml
version: '3'
volumes:
  db-data:
services:
  mysql:
    image: mysql:5.7
    working_dir: /application
    volumes:
      - db-data:/application
    environment:
      - MYSQL_ROOT_PASSWORD=docker_root
      - MYSQL_DATABASE=sf4_db
      - MYSQL_USER=sf4_user
      - MYSQL_PASSWORD=sf4_pw
    ports:
      - "8306:3306"
    networks:
      - app_network
  webserver:
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - app_network
  php-fpm:
    build: docker/php-fpm
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini
    environment:
      XDEBUG_CONFIG: "remote_host=${localIp}"
    networks:
      - app_network

#Docker Networks
networks:
  app_network:
    driver: bridge